image: maven:latest

cache:
  paths:
    - SESEditor/target/

build:
  stage: build
  script:
    - ls -l
    - cd SESEditor
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test