name: Java CI

on: [push]

jobs:
  all:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        target: [PESEditor, SESEditor]
        goal: [ compile, verify, "package -DskipTests" ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run Maven
        run: mvn --file ${{ matrix.target }} --batch-mode --update-snapshots ${{ matrix.goal }}
        continue-on-error:  ${{ matrix.goal == 'verify' && matrix.target == 'SESEditor' }} # TODO remove this once SESEditor passes the test suite
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.target}}
          path: "${{ matrix.target }}/target/*.jar"
        if: matrix.goal == 'package -DskipTests'
